.\" Man page for wk.
.\" Adapted from the example at https://www.systutorials.com/docs/linux/man/7-man-pages/
.TH WK 1 "January 2024" "1.0.0" "wk man page"
.SH NAME
wk \- Count bytes, lines, or words in a file (wc clone written in Kotlin)
.SH SYNOPSIS
.B wk
.RI [ options ]
.I filename
.SH DESCRIPTION
.B wk
counts the number of bytes, lines, or words in a file and writes the result to the standard output.
.SH OPTIONS
.TP
.B \-c
Count the number of bytes in the input file.
.TP
.B \-l
Count the number of lines in the input file.
.TP
.B \-m
Count the number of characters in the input file. If the current locale does not support multibyte characters, this is equivalent to the \-c option. This cancels out any prior usage of the \-c option.
.TP
.B \-w
Count the number of words in the input file.
.SH ARGUMENTS
.TP
.I filename
The path to the input file.
.SH EXAMPLES
Count the number of lines in a file:
.PP
.B wk -l myfile.txt
.SH SEE ALSO
.BR wc (1)
.SH AUTHOR
Vladas Maier <vladas.mr@gmail.com>.
.SH COPYRIGHT
Copyright © 2024 Vladas Maier. This is free software; you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.
.\" End of man page
